asm/Models/cartItem.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace asm.Models
{
    public class cartItem
    {
        [Key]
        public long ProductId { get; set; }
        [StringLength(250)]
        public string Name { get; set; }
        [StringLength(250)]
        public string Image { get; set; }
        [Column(TypeName = "decimal(18, 0)")]
        public decimal Price { get; set; }

        public int Quantity { get; set; }
    }
}

asm/Controllers/BillController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Http;
using asm.Models;
namespace asm.Controllers
{
    public class BillController : Controller
    {
        private readonly fullContext _context;

        public BillController(fullContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            ViewBag.messtc = HttpContext.Session.GetString("messtc");
            ViewBag.messtb = HttpContext.Session.GetString("messtb");
            var cart = JsonConvert.DeserializeObject(HttpContext.Session.GetString("cartItem"));
            ViewBag.Bill = cart;
            ViewBag.total = HttpContext.Session.GetString("total");

            return View();
        }
        public IActionResult Pay(string? money)
        {
            if (money == null)
            {
                return NotFound();
            }
            List<Product> product = new List<Product>();
            product = _context.Products.ToList();
            List<cartItem> cartItems = new List<cartItem>();
            cartItems = _context.cartItems.ToList();
            string mon = HttpContext.Session.GetString("total");
            if (Convert.ToInt64(money) - Convert.ToInt64(mon) >= 0)
            {
                Cart cart = new Cart();
                cart.CreateDate = DateTime.Now;
                cart.Status = true;
                _context.Add(cart);
                _context.SaveChanges();
                for (int i = 0; i < cartItems.Count; i++)
                {

                    CartDetail cartDetail = new CartDetail();
                    cartDetail.CartId = cart.Id;
                    cartDetail.ProductId = cartItems[i].ProductId;
                    cartDetail.Price = cartItems[i].Price;
                    cartDetail.Quantity = cartItems[i].Quantity;
                    cartDetail.Status = true;
                    _context.Add(cartDetail);
                }
                for (int i = 0; i < cartItems.Count; i++)
                {
                    for (int j = 0; j < product.Count; j++)
                    {
                        if (cartItems[i].ProductId == product[j].Id)
                        {
                            product[j].Quantity = product[j].Quantity - cartItems[i].Quantity;
                        }
                    }
                }
                foreach (var x in product)
                {
                    _context.Update(x);
                }
                HttpContext.Session.SetString("messtc", "Thanh toán thành công");
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            HttpContext.Session.SetString("messtb", "Thanh toán thất bại");
            return RedirectToAction(nameof(Index));
        }
    }
}

asm/Controllers/cartItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using asm.Models;
using Microsoft.AspNetCore.Http;
using Newtonsoft.Json;
using asm.Controllers;
namespace asm.Controllers
{
    public class cartItemsController : Controller
    {
        private readonly fullContext _context;

        public cartItemsController(fullContext context)
        {
            _context = context;
        }

        // GET: cartItems
        public async Task<IActionResult> Index()
        {
            List<cartItem> cartItem = new List<cartItem>();
            cartItem = _context.cartItems.ToList();
            string temb = JsonConvert.SerializeObject(cartItem);
            HttpContext.Session.SetString("cartItem", temb);
            ViewBag.Total = cartItem.Sum(p => p.Quantity * p.Price);
            HttpContext.Session.SetString("total", cartItem.Sum(p => p.Quantity * p.Price).ToString());
            return View(await _context.cartItems.ToListAsync());
        }

        // GET: cartItems/Details/5
        public async Task<IActionResult> Details(long? id)
        {

            if (id == null)
            {
                return NotFound();
            }

            var cartItem = await _context.cartItems
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (cartItem == null)
            {
                return NotFound();
            }

            return View(cartItem);
        }
        public IActionResult cong(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            cartItem cartItem = new cartItem();
            cartItem = _context.cartItems.Where(c => c.ProductId == id).FirstOrDefault();
            if (cartItem == null)
            {
                return NotFound();
            }
            Product product = new Product();
            product = _context.Products.Where(c => c.Id == id).FirstOrDefault();
            if (cartItem.Quantity + 1 > product.Quantity)
            {

                return RedirectToAction(nameof(Index));

            }
            else
            {
                cartItem.Quantity++;
                _context.Update(cartItem);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }


        }
        public IActionResult tru(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            cartItem cartItem = new cartItem();
            cartItem = _context.cartItems.Where(c => c.ProductId == id).FirstOrDefault();
            if (cartItem == null)
            {
                return NotFound();
            }
            if (cartItem.Quantity == 1)
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                cartItem.Quantity--;
                _context.Update(cartItem);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }


        }
        // GET: cartItems/Create
        public IActionResult Create(long id)
        {

            if (id == null)
            {
                return NotFound();
            }
         
            if (HttpContext.Session.GetString("user") == "" || HttpContext.Session.GetString("user") == null)
            {

                HttpContext.Session.SetString("messAddCart", "Đăng nhập để mua hàng");
                return RedirectToAction("Index", "Home");
            }
            else
            {
                HttpContext.Session.SetString("messAddCart", "");
            }

            cartItem cartItem = new cartItem();
            var cart = _context.Products.Where(p => p.Id == id).FirstOrDefault();
            if (!IsExit(id))
            {
                cartItem.ProductId = id;
                cartItem.Name = cart.Name;
                cartItem.Price = cart.Price;
                cartItem.Image = cart.Image;
                cartItem.Quantity = 1;
                _context.Add(cartItem);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            else if (IsExit(id))
            {
                var cartItemUPdate = _context.cartItems.Where(p => p.ProductId == id).FirstOrDefault();
                cartItemUPdate.Quantity++;
                _context.Update(cartItemUPdate);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            else
            {
                ViewData["NotFound"] = "Not Found Product";
            }
            return RedirectToAction(nameof(Index));
        }
        public bool IsExit(long? id)
        {
            if (_context.cartItems.Where(p => p.ProductId == id).FirstOrDefault() != null)
            {
                return true;
            }
            return false;
        }
        // POST: cartItems/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.


        // GET: cartItems/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cartItem = await _context.cartItems.FindAsync(id);
            if (cartItem == null)
            {
                return NotFound();
            }
            return View(cartItem);
        }

        // POST: cartItems/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("ProductId,Name,Image,Price,Quantity")] cartItem cartItem)
        {
            if (id != cartItem.ProductId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cartItem);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!cartItemExists(cartItem.ProductId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(cartItem);
        }

        // GET: cartItems/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cartItem = await _context.cartItems
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (cartItem == null)
            {
                return NotFound();
            }


            _context.cartItems.Remove(cartItem);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // POST: cartItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]

        private bool cartItemExists(long id)
        {
            return _context.cartItems.Any(e => e.ProductId == id);
        }
    }
}

asm/Views/cartItems/Create.cshtml
@model asm.Models.cartItem

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>cartItem</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input asp-for="Image" class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>


asm/Views/cartItems/Delete.cshtml
@model asm.Models.cartItem

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>cartItem</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Image)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ProductId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

asm/Views/cartItems/Details.cshtml
@model asm.Models.cartItem

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>cartItem</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Image)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ProductId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

asm/Views/cartItems/Edit.cshtml
@model asm.Models.cartItem

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>cartItem</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ProductId" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input asp-for="Image" class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>


asm/Views/cartItems/Index.cshtml
@model IEnumerable<asm.Models.cartItem>

@{
    var total = ViewBag.Total;
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/dash/css/kechan.css" />
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">


<table class="table">
    <thead>
        <tr>
            <th scope="col">  STT</th>
            <th scope="col">    @Html.DisplayNameFor(model => model.Name)</th>
            <th scope="col">    @Html.DisplayNameFor(model => model.Image)</th>
            <th scope="col">   @Html.DisplayNameFor(model => model.Price)</th>
            <th scope="col">  @Html.DisplayNameFor(model => model.Quantity)</th>
            <th></th>
        </tr>
    </thead>
    <tbody>

        @{
            int index = 1;
            foreach (var item in Model)
            {
              
                <tr>
                    <th scope="row">@index</th>
                    <td>     @Html.DisplayFor(modelItem => item.Name)</td>
                    <td>  <img src=" @Html.DisplayFor(modelItem => item.Image)" class="img-thumbnail" alt=" @Html.DisplayFor(modelItem => item.Name)"></td>
                    <td>   @item.Price.ToString("n0") VND</td>
                    <td><a class="kechan" asp-controller="cartItems" asp-action="tru" asp-route-id="@item.ProductId">-&nbsp; </a> @item.Quantity<a class="kechan" asp-controller="cartItems" asp-action="cong" asp-route-id="@item.ProductId">&nbsp;  +</a>  </td>
                    <td>
                    <td>
                     
                        <a asp-action="Delete" asp-route-id="@item.ProductId">Delete</a>
                    </td>
                    </td>

                </tr>
               
                index++;
            }
            <tr>
                <td>Thành tiền</td>
                <td>@total.ToString("n0") VND</td>
            </tr>
        }

    </tbody>

</table>
<a class="kechan" asp-action="Index" asp-controller="Home">Back</a>
<a asp-controller="Bill" asp-action="Index">Thanh toán </a>