asm/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using asm.Models;
using Microsoft.AspNetCore.Http;

namespace asm.Controllers
{
    public class CustomersController : Controller
    {
        private readonly fullContext _context;

        public CustomersController(fullContext context)
        {
            _context = context;
        }

        // GET: Customers
        public async Task<IActionResult> Index()
        {
            string position = HttpContext.Session.GetString("position");
            if (position == "1")
            {
                return View(await _context.Customers.ToListAsync());
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }

        }

        // GET: Customers/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = await _context.Customers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (customer == null)
            {
                return NotFound();
            }
            string position = HttpContext.Session.GetString("position");
            if (position == "1")
            {
                return View(customer);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
         
        }

        // GET: Customers/Create
        public IActionResult Create()
        {
            string position = HttpContext.Session.GetString("position");
            if (position == "1")
            {
                return View();
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }

          

        }

        // POST: Customers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Address,Phone,User,PassWord,Position,Status")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                _context.Add(customer);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(customer);
        }

        // GET: Customers/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = await _context.Customers.FindAsync(id);
            if (customer == null)
            {
                return NotFound();
            }
            return View(customer);
        }

        // POST: Customers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("Id,Name,Address,Phone,User,PassWord,Position,Status")] Customer customer)
        {
            if (id != customer.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(customer);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CustomerExists(customer.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(customer);
        }

        // GET: Customers/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = await _context.Customers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (customer == null)
            {
                return NotFound();
            }

            return View(customer);
        }

        // POST: Customers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var customer = await _context.Customers.FindAsync(id);
            _context.Customers.Remove(customer);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CustomerExists(long id)
        {
            return _context.Customers.Any(e => e.Id == id);
        }
    }
}

asm/Controllers/LoginController.cs
using asm.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace asm.Controllers
{
    public class LoginController : Controller
    {
        private readonly fullContext _context;

        public LoginController(fullContext context)
        {
            _context = context;
        }
        public IActionResult login()
        {
            return View();
        }
        [HttpPost]
        public IActionResult veryfi(string user, string pass)
        {
            Customer customer = new Customer();
            customer = _context.Customers.ToList().Where(c => c.User == user && c.PassWord == pass).FirstOrDefault();
            if (customer != null)
            {
                HttpContext.Session.SetString("position", customer.Position.ToString());
                ViewBag.loginFail = "";
                HttpContext.Session.SetString("user", user);
                ViewBag.user = user;
                HttpContext.Session.SetString("messAddCart", "Đã đăng nhập");
                return RedirectToAction("Index", "Home");
            }
            else
            {
                HttpContext.Session.SetString("loginFail", "Đăng nhập thất bại");
                ViewBag.loginFail = "Đăng nhập thất bại";
                return View("login");
            }

        }

        public IActionResult lout()
        {

            HttpContext.Session.SetString("user", "");
            HttpContext.Session.SetString("position", "");
            ViewBag.loginFail = "";
            HttpContext.Session.SetString("messAddCart", "");
            return RedirectToAction("Index", "Home");



        }
    }
}

asm/Views/Shared/_Layout.cshtml
<!--A Design by W3layouts
Author: W3layout
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->

<!DOCTYPE HTML>

<html>
<head>
    <title>Free Home Shoppe Website Template | Home :: w3layouts</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link href="~/dash/css/style.css" rel="stylesheet" type="text/css" media="all" />
    <link href="~/dash/css/slider.css" rel="stylesheet" type="text/css" media="all" />
    <script type="text/javascript" src="~/dash/js/jquery-1.7.2.min.js"></script>
    <script type="text/javascript" src="~/dash/js/move-top.js"></script>
    <script type="text/javascript" src="~/dash/js/easing.js"></script>
    <script type="text/javascript" src="~/dash/js/startstop-slider.js"></script>
</head>
<body>
    <div class="wrap">
        <div class="header">
            <div class="headertop_desc">
                <div class="call">
                    <p><span>Need help?</span> call us <span class="number">1-22-3456789</span></span></p>
                </div>
                <div class="account_desc">
                    <ul>
                        <li><a href="#">Register</a></li>
                        <li><a asp-controller="Login" asp-action="login">Login</a></li>
                        <li><a asp-controller="Customers" asp-action="Index">Quản lý sản tài khoản</a></li>
                        <li><a asp-controller="Login" asp-action="lout">Checkout</a></li>
                        <li><a href="#">My Account</a></li>
                      
                    </ul>
                </div>
                <div class="clear"></div>
            </div>
            <div class="header_top">
                <div class="logo">
                    <a href="index.html"><img src="~/dash/images/logo.png" alt="" /></a>
                </div>
                <div class="cart">
                    <p>
                        Welcome to our Online Store! <span>Cart:</span><div id="dd" class="wrapper-dropdown-2">
                            0 item(s) - $0.00
                            <ul class="dropdown">
                                <li>you have no items in your Shopping cart</li>
                            </ul>
                        </div>
                    </p>
                </div>
                <script type="text/javascript">
                    function DropDown(el) {
                        this.dd = el;
                        this.initEvents();
                    }
                    DropDown.prototype = {
                        initEvents: function () {
                            var obj = this;

                            obj.dd.on('click', function (event) {
                                $(this).toggleClass('active');
                                event.stopPropagation();
                            });
                        }
                    }

                    $(function () {

                        var dd = new DropDown($('#dd'));

                        $(document).click(function () {
                            // all dropdowns
                            $('.wrapper-dropdown-2').removeClass('active');
                        });

                    });

                </script>
                <div class="clear"></div>
            </div>
            <div class="header_bottom">
                <div class="menu">
                    <ul>
                        <li class="active"><a href="">Home</a></li>
                        <li><a  asp-controller="Customers" asp-action="Index">Customers</a></li>
                        <li><a >Delivery</a></li>
                        <li><a href="">News</a></li>
                        <li><a href="">Contact</a></li>
                        <div class="clear"></div>
                    </ul>
                </div>
                <div class="search_box">
                    <form>
                        <input type="text" value="Search" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Search';}"><input type="submit" value="">
                    </form>
                </div>
                <div class="clear"></div>
            </div>
            @RenderSection("slide", required: false)

        </div>
        <div class="main">
            @RenderBody()
        </div>
    </div>
    <div class="footer">
        <div class="wrap">
            <div class="section group">
                <div class="col_1_of_4 span_1_of_4">
                    <h4>Information</h4>
                    <ul>
                        <li><a href="">About Us</a></li>
                        <li><a href="">Customer Service</a></li>
                        <li><a href="">Advanced Search</a></li>
                        <li><a href="">Orders and Returns</a></li>
                        <li><a href="">Contact Us</a></li>
                    </ul>
                </div>
                <div class="col_1_of_4 span_1_of_4">
                    <h4>Why buy from us</h4>
                    <ul>
                        <li><a href="#">About Us</a></li>
                        <li><a href="#">Customer Service</a></li>
                        <li><a href="#">Privacy Policy</a></li>
                        <li><a href="#">Site Map</a></li>
                        <li><a href="#">Search Terms</a></li>
                    </ul>
                </div>
                <div class="col_1_of_4 span_1_of_4">
                    <h4>My account</h4>
                    <ul>
                        <li><a href="#">Sign In</a></li>
                        <li><a href="#">View Cart</a></li>
                        <li><a href="#">My Wishlist</a></li>
                        <li><a href="#">Track My Order</a></li>
                        <li><a href="#">Help</a></li>
                    </ul>
                </div>
                <div class="col_1_of_4 span_1_of_4">
                    <h4>Contact</h4>
                    <ul>
                        <li><span>+91-123-456789</span></li>
                        <li><span>+00-123-000000</span></li>
                    </ul>
                    <div class="social-icons">
                        <h4>Follow Us</h4>
                        <ul>
                            <li><a href="#" target="_blank"><img src="~/dash/images/facebook.png" alt="" /></a></li>
                            <li><a href="#" target="_blank"><img src="~/dash/images/twitter.png" alt="" /></a></li>
                            <li><a href="#" target="_blank"><img src="~/dash/images/skype.png" alt="" /> </a></li>
                            <li><a href="#" target="_blank"> <img src="~/dash/images/dribbble.png" alt="" /></a></li>
                            <li><a href="#" target="_blank"> <img src="~/dash/images/linkedin.png" alt="" /></a></li>
                            <div class="clear"></div>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="copy_right">
            <p>&copy; 2013 home_shoppe. All rights reserved </p>
        </div>
    </div>
    <script type="text/javascript">
        $(document).ready(function () {
            $().UItoTop({ easingType: 'easeOutQuart' });

        });
    </script>
    <a href="#" id="toTop"><span id="toTopHover"> </span></a>
</body>
</html>
